#ifndef ROUTEMAP_H
#define ROUTEMAP_H

enum RouteMapCode {
    ROUTE_USER = 1,
    ROUTE_USER_ALL,
    ROUTE_LOCATION = 10,
    ROUTE_LOCATION_CURRENT,
    ROUTE_BRANCH = 20,
    ROUTE_VEHICLE = 30,
    ROUTE_VEHICLE_TYPE = 40,
    ROUTE_FAILED = 50,
    ROUTE_CURRENT_TIME
};

#endif